language: node_js
node_js: '4.3.2'

sudo: false
dist: trusty

cache:
  directories:
  - node_modules
  - $HOME/.cache

before_install:
- |
  if [ -n "$TRAVIS_BRANCH" ]; then
    export S3_PREFIX="branch-$TRAVIS_BRANCH"
  fi

  if [ -n "$TRAVIS_TAG" ]; then
    export S3_PREFIX="tag-$TRAVIS_TAG"
  fi

  export STACK_NAME="aws-lambda-ffmpeg-$S3_PREFIX"
- npm i -g npm@latest && npm i -g gulp && npm -v

before_script:
- gulp aws:default

script:
- npm test
- npm run test-integration

after_script:
- gulp aws:deleteStack
